[system]
compatible=milkv-duo256m

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=ext4

[slot.rootfs.1]
device=/dev/mmcblk0p3
type=ext4

[slot.data.0]
device=/dev/mmcblk0p4
type=ext4
